
five = ["I really like toast", 
        "I like it best cold", 
        "Beans are kind to hearts", 
        "And then do big farts", 
        "The sky is so blue", 
        "I love the summer", 
        "Refrigerator",
        "A white plastic spork",
        "Can't wait to decide",
        "You can eat it too",
        "You may not know this",
        "This is a haiku",
        "It's okay with me",
        "I so dislike frogs",
        "Enter second act",
        "Trying to masterbate",
        "A poor girls memoir",
        "Scared. Old man. CIGAR!",
        "I didn't grope you",
        "Some might say thank you",
        "Green and speckled legs",
        "In a pouch I grow",
        "Splash in cool water",
        "Strange creatures I know",
        "Easter bunny hides",
        "Kids look everywhere",
        "Snowflakes are our friends",
        "Making white blankets",
        "I see you driving",
        "And I'm like haiku",
        "Hippopotamus",
        "Annihilation",
        "Truths are absolute",
        "Not true, WHAMMY BAR!",
        "You think you're big",
        "This is not so hard",
        "Tittering monkey",
        "And thinks himself tall",
        "Squish squash sling that slang",
        "Like my boomerang",
        "Whole seasons are spent",
        "None calls it easy",
        "There's nuts and there's fruits",
        "Always to be squashed",
        "That is not my fault",
        "I can't take credit",
        "Brains brains brains brains brains",
        "Chairs are like tables",
    ]