
five = ["I really like toast", 
        "I like it best cold", 
        "Beans are kind to hearts", 
        "And then do big farts", 
        "The sky is so blue", 
        "I love the summer", 
        "Refrigerator",
        "A white plastic spork",
        "Can't wait to decide",
        "You can eat it too",
        "You may not know this",
        "This is a haiku",
        "It's okay with me",
        "I so dislike frogs",
        "Enter second act",
        "Trying to masterbate",
        "A poor girls memoir",
        "Scared. Old man. CIGAR!",
        "I didn't grope you",
        "Some might say thank you",
    ]