
seven = [   "The sun is so warm up high", 
            "It is yummy when it's hot", 
            "I like to eat them daily",
            "Is on the opposite side",
            "I cannot help my spasms",
            "Wax my chest or perm my hair?",
            "To get the perfect six pack",
            "With wonder and surprises",
            "We take time to celebrate",
            "Today's coffee may be strong",
            "Can you keep a secret babe?",
            "Boobs. Pause for laugh and applause",
            "The samurai is coming",
            "Try to count the syllables",
            "It is difficult to count",
            "Are the syllables correct",
            "Poetry generation",
            "Hop on logs and lily pads",
            "On a southern continent",
            "Easter eggs are out of sight",
            "They descend when winter comes",
            "Will really only make sense",
            "Into some technology",
            "But at least I saved Earth",
            "I started them off just fine",
            "Have started these in order",
            "In fall the clinging plum drops",
            "Like I paddle my canoe",
            "In spring he climbs treetops",
            "With your fancy little words",
            "Never learned to play guitar",
            "Round town with the girl I love",
      ]